# Generated by Django 3.0.8 on 2022-05-06 14:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=1000, unique=True)),
                ('album_art', models.ImageField(blank=True, default='', upload_to='album_arts')),
                ('about_album', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('plays', models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('album_latest', models.BooleanField(default=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='category_images')),
                ('about_category', models.TextField()),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=1000, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='events_images')),
                ('event_by', models.CharField(max_length=1000)),
                ('about_event', models.TextField(max_length=1000)),
                ('event_date', models.DateTimeField()),
                ('event_venue', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ('event_date',),
            },
        ),
        migrations.CreateModel(
            name='slider_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image_1', models.ImageField(blank=True, upload_to='slider_images')),
                ('tag_line_1', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=1000)),
                ('image_2', models.ImageField(blank=True, upload_to='slider_images')),
                ('tag_line_2', models.CharField(default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'slider_image',
                'verbose_name_plural': 'slider_images',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('slug', models.SlugField(default='', max_length=1000)),
                ('feature', models.CharField(blank=True, default='', max_length=1000)),
                ('song', models.FileField(upload_to='songs/%Y/%m/%d')),
                ('song_art', models.ImageField(blank=True, upload_to='song_art/%Y/%m/%d')),
                ('about_song', models.TextField()),
                ('plays', models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='muse.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='muse.Category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='muse.Category'),
        ),
        migrations.AddField(
            model_name='album',
            name='users_like',
            field=models.ManyToManyField(blank=True, default='', related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
