# Generated by Django 3.0.8 on 2022-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider_images',
            options={'verbose_name': 'slider_image', 'verbose_name_plural': 'slider_images'},
        ),
        migrations.RemoveField(
            model_name='slider_images',
            name='name',
        ),
        migrations.AlterField(
            model_name='slider_images',
            name='slug',
            field=models.SlugField(default='welcome-ingoma', editable=False, max_length=1000),
        ),
    ]
