# Generated by Django 5.0.2 on 2025-08-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributions',
            name='description',
        ),
        migrations.AddField(
            model_name='contributions',
            name='role',
            field=models.CharField(choices=[('writer', 'Writer'), ('singer', 'Singer'), ('producer', 'Producer'), ('editor', 'Editor'), ('director', 'Director'), ('other', 'Other')], default='singer', max_length=255),
        ),
    ]
