# Generated by Django 3.0.8 on 2022-05-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0002_auto_20220506_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default='single', on_delete=django.db.models.deletion.CASCADE, to='muse.Album'),
        ),
    ]
