# Generated by Django 3.0.8 on 2022-05-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0006_auto_20220506_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_art',
            field=models.ImageField(default='', upload_to='album_arts'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='category_images'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to='events_images'),
        ),
        migrations.AlterField(
            model_name='slider_images',
            name='image_1',
            field=models.ImageField(upload_to='slider_images'),
        ),
        migrations.AlterField(
            model_name='slider_images',
            name='image_2',
            field=models.ImageField(upload_to='slider_images'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_art',
            field=models.ImageField(upload_to='song_art/%Y/%m/%d'),
        ),
    ]
