# Generated by Django 3.0.8 on 2022-05-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0007_auto_20220506_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='', max_length=1000, unique=True),
        ),
    ]
