# Generated by Django 5.0.2 on 2025-08-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0009_alter_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='x',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
