# Generated by Django 3.0.8 on 2022-05-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0009_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='song',
        ),
    ]
