# Generated by Django 3.0.8 on 2022-05-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0010_auto_20220509_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created',), 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
