# Generated by Django 3.0.8 on 2022-05-10 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muse', '0011_auto_20220510_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('free', 'free'), ('purchase', 'purchase')], default='free', max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='about_event',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_by',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_venue',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='slider_images',
            name='slug',
            field=models.SlugField(default='welcome-ingoma', editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='slider_images',
            name='tag_line_2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='song',
            name='feature',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='', max_length=500, unique=True),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='muse.Song')),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
                'ordering': ('created',),
            },
        ),
    ]
