# Generated by Django 3.0.8 on 2022-05-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0013_auto_20220512_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
