# Generated by Django 3.0.8 on 2022-05-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0014_sitedata_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
