# Generated by Django 3.0.8 on 2022-05-16 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muse', '0016_sales_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='users_like',
            field=models.ManyToManyField(blank=True, default='', editable=False, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
