# Generated by Django 3.0.8 on 2022-05-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0017_auto_20220516_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_art',
            field=models.ImageField(upload_to='album_arts'),
        ),
    ]
