# Generated by Django 3.0.8 on 2022-05-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0019_artistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='quote_one',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='quote_two',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
