# Generated by Django 3.0.8 on 2022-05-18 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muse', '0020_auto_20220517_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='plays',
        ),
        migrations.RemoveField(
            model_name='song',
            name='plays',
        ),
        migrations.AddField(
            model_name='song',
            name='plays',
            field=models.ManyToManyField(editable=False, related_name='song_plays', to=settings.AUTH_USER_MODEL),
        ),
    ]
