# Generated by Django 3.0.8 on 2022-05-18 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muse', '0021_auto_20220518_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='plays',
            field=models.ManyToManyField(related_name='song_plays', to=settings.AUTH_USER_MODEL),
        ),
    ]
