# Generated by Django 3.0.8 on 2022-05-18 10:11

from django.conf import settings
from django.db import migrations, models
import muse.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muse', '0022_auto_20220518_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='plays',
            field=models.ManyToManyField(default=None, related_name='song_plays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='songs/%Y/%m/%d', validators=[muse.models.ExtensionValidator(['mp3'])]),
        ),
    ]
