# Generated by Django 3.0.8 on 2022-05-28 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muse', '0028_auto_20220520_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('active_role', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.AlterField(
            model_name='slider_images',
            name='slug',
            field=models.SlugField(default='welcome-ingoma', max_length=500),
        ),
        migrations.AlterField(
            model_name='song',
            name='about_song',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
