# Generated by Django 3.0.8 on 2022-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0029_auto_20220528_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='team',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitter',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='what_we_do',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='where_we_are',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='why_work_with_us',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='active_role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
