# Generated by Django 3.0.8 on 2022-05-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0030_auto_20220528_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
