# Generated by Django 3.0.8 on 2022-05-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0031_sales_cleared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='slug',
        ),
    ]
