# Generated by Django 3.0.8 on 2022-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0032_remove_sales_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='disk_immage',
            field=models.ImageField(blank=True, upload_to='disk_image/'),
        ),
    ]
