# Generated by Django 3.0.8 on 2022-05-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0033_sitedata_disk_immage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedata',
            old_name='disk_immage',
            new_name='disk_image',
        ),
    ]
