# Generated by Django 3.0.8 on 2022-06-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0034_auto_20220528_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='i_agree',
            field=models.BooleanField(default=False),
        ),
    ]
