# Generated by Django 3.0.8 on 2022-06-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0035_artistprofile_i_agree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
