# Generated by Django 5.0.2 on 2024-03-31 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0036_auto_20220620_1042'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='slider_images',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='about_song',
            new_name='song_bio',
        ),
        migrations.RemoveField(
            model_name='album',
            name='users_like',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='i_agree',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='quote_one',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='quote_two',
        ),
        migrations.RemoveField(
            model_name='song',
            name='category',
        ),
        migrations.RemoveField(
            model_name='song',
            name='feature',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='features',
            field=models.ManyToManyField(default='', related_name='features', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(related_name='Genres', to='muse.category'),
        ),
        migrations.AddField(
            model_name='song',
            name='released',
            field=models.CharField(choices=[('Released', 'Released'), ('Draft', 'Draft')], default='new song', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='muse.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stream',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muse.song'),
        ),
    ]
