# Generated by Django 5.0.2 on 2024-03-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0037_stream_delete_slider_images_delete_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='plays',
        ),
    ]
