# Generated by Django 5.0.2 on 2024-04-01 06:10

import django.db.models.deletion
import muse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0039_stream_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muse.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='muse.category'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='songs/%Y/%m/%d', validators=[muse.models.ExtensionValidator(['mp3', 'm4a'])]),
        ),
        migrations.AlterField(
            model_name='stream',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='muse.song'),
        ),
    ]
