# Generated by Django 5.0.2 on 2024-04-01 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0040_alter_song_album_alter_song_genre_alter_song_song_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, related_name='features', to=settings.AUTH_USER_MODEL),
        ),
    ]
