# Generated by Django 5.0.2 on 2024-04-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0041_alter_song_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
