# Generated by Django 5.0.2 on 2024-04-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0042_song_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='stream_date',
            new_name='timestamp',
        ),
    ]
