# Generated by Django 5.0.2 on 2024-04-12 16:10

import django.db.models.deletion
import muse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0045_album_rating_alter_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='demo',
            field=models.FileField(blank=True, null=True, upload_to='demos/%Y/%m/%d', validators=[muse.models.ExtensionValidator(['mp3', 'm4a'])]),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='muse.album'),
        ),
    ]
