# Generated by Django 5.0.2 on 2024-04-18 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0046_song_demo_alter_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genre_profiles', to='muse.category'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
