# Generated by Django 5.0.2 on 2024-04-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0047_artistprofile_genre_alter_artistprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='category',
            new_name='genre',
        ),
    ]
