# Generated by Django 5.0.2 on 2024-05-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0048_rename_category_album_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='country',
            field=models.CharField(default='Zimbabwe', max_length=50),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='user_account',
            field=models.CharField(choices=[('basic', 'basic'), ('premium', 'premium'), ('platimum', 'platimum')], default='basic', max_length=50),
        ),
        migrations.AddField(
            model_name='sales',
            name='email',
            field=models.EmailField(default='sales@ingoma.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('Ecocash USD', 'Ecocash USD'), ('Ecocash ZIG', 'Ecocash ZIG'), ('InnBucks', 'InnBucks'), ('VISA/Mastercard', 'VISA/Mastercard')], default='Ecocash ZIG', max_length=20),
        ),
        migrations.AddField(
            model_name='sales',
            name='phone',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='poll_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
