# Generated by Django 5.0.2 on 2024-05-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0050_sales_user_alter_sales_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_and_Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='news_and_updates/')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Update',
                'verbose_name_plural': 'Updates',
            },
        ),
        migrations.AlterField(
            model_name='song',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=3, null=True),
        ),
    ]
