# Generated by Django 5.0.2 on 2024-05-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0051_news_and_updates_alter_song_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='news_and_updates',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], max_length=11),
        ),
    ]
