# Generated by Django 5.0.2 on 2024-06-08 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0052_remove_sales_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=2, max_digits=3)),
                ('artist', models.ManyToManyField(related_name='artist_share', to=settings.AUTH_USER_MODEL)),
                ('song', models.ManyToManyField(related_name='owner_song', to='muse.song')),
            ],
            options={
                'verbose_name': 'Ownership',
                'verbose_name_plural': 'Ownerships',
            },
        ),
    ]
