# Generated by Django 5.0.2 on 2024-08-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0054_remove_comments_email_remove_comments_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
