# Generated by Django 5.0.2 on 2024-08-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0055_delete_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News_and_Updates',
        ),
    ]
