# Generated by Django 5.0.2 on 2024-08-21 15:49

import muse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0057_alter_album_id_alter_artistprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile-pictures', validators=[muse.models.validate_image_size]),
        ),
    ]
