# Generated by Django 5.0.2 on 2024-08-22 18:52

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0058_alter_artistprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='song',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='released',
        ),
        migrations.AddField(
            model_name='song',
            name='song_status',
            field=models.CharField(choices=[('Released', 'Released'), ('Draft', 'Draft')], default='Draft', max_length=20),
        ),
    ]
