# Generated by Django 5.0.2 on 2024-08-30 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0059_alter_song_managers_remove_song_released_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='song',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_status',
        ),
        migrations.AddField(
            model_name='song',
            name='released',
            field=models.CharField(choices=[('Released', 'Released'), ('Draft', 'Draft')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='total_streams',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='album_genre', to='muse.category'),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='', max_length=500),
        ),
    ]
