# Generated by Django 5.0.2 on 2025-08-15 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist_admin', '0001_initial'),
        ('muse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistearnings',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_earnings', to='muse.artistprofile'),
        ),
        migrations.AddField(
            model_name='artistshare',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_artist_share', to='muse.artistprofile'),
        ),
        migrations.AddField(
            model_name='artistshare',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_earnings_share', to='muse.song'),
        ),
        migrations.AddField(
            model_name='payment',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_payments', to='muse.song'),
        ),
        migrations.AddField(
            model_name='artistshare',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_song_share', to='artist_admin.payment'),
        ),
        migrations.AddField(
            model_name='artistearnings',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_earnings_payment', to='artist_admin.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_payments', to='artist_admin.paymentmethod'),
        ),
    ]
