# Generated by Django 5.0.2 on 2025-08-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_admin', '0003_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistearnings',
            name='account',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10),
        ),
    ]
